### ISSUE TITLE
Error of code and error on browswe

### ISSUE THREAD

**Issue by cogitas3d** [livro-aberto/SphinxEdit#16]
Hi!

I try to follow the steps and I  had to change:

`cp conf_default.py conf.py`

to

`cp config_default.py config.py`

So, when I enter on http://127.0.0.1:5000/ I have this message:

`Internal serve error
IOError(2, 'No such file or directory')
Execution stack
Traceback (most recent call last):
File "/home/cogitas3d/Programs/SphinxEdit-master/vir/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/home/cogitas3d/Programs/SphinxEdit-master/vir/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/cogitas3d/Programs/SphinxEdit-master/application/views.py", line 76, in edit
rst = load_file(branch_source_path)
File "/home/cogitas3d/Programs/SphinxEdit-master/application/tools/__init__.py", line 28, in load_file
with codecs.open(path, 'r', 'utf-8') as content_file:
File "/home/cogitas3d/Programs/SphinxEdit-master/vir/lib/python2.7/codecs.py", line 898, in open
file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'repos/source/index.rst'`

**Comment by augustoteixeira** [comment]
I think it is fixed now, reopen if this is not the case for you.

Hope you find it useful. If you are interested, we are developing a better interface for this in another repository.

**Comment by cogitas3d** [comment]
All right it worked perfectly, thank you!

I'm interested in the other version too!

I'm writing a documentation using Sphinx: http://www.ciceromoraes.com.br/doc/pt_br/OrtogOnBlender/Protocolo_Planejamento.html

A big hug!
